language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.3
  - 5.4
  - 5.5
env:
  matrix:
    - MAGENTO_VERSION="1.5.0.1"
    - MAGENTO_VERSION="1.6.0.0"
    - MAGENTO_VERSION="1.6.1.0"
    - MAGENTO_VERSION="1.6.2.0"
    - MAGENTO_VERSION="1.7.0.0"
    - MAGENTO_VERSION="1.7.0.1"
    - MAGENTO_VERSION="1.7.0.2"
    - MAGENTO_VERSION="1.8.0.0"
    - MAGENTO_VERSION="1.8.1.0"
    - MAGENTO_VERSION="1.9.0.0"
    - MAGENTO_VERSION="1.9.0.1"
before_install:
  - mkdir magento/
  - cp -f .travis/composer.json composer.json
  - composer install --dev
before_script:
  - phpenv rehash
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
